name: CMake

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  BUILD_TYPE: Release
jobs:
  build_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3.0.6
        with:
           path: ${{github.workspace}}\build\_deps
           key: wincache
      - name: Configure CMake
        run: cmake ./ -B ${{github.workspace}}\build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}}
      - name: Copy
        run: |
          xcopy ${{github.workspace}}\TGEngine\application\assets\ ${{github.workspace}}\build\Release\assets\ /S/I/Y
          xcopy ${{github.workspace}}\TGEngine\test\assets\*.* ${{github.workspace}}\build\Release\assets\ /S/I/Y
          copy ${{github.workspace}}\TGEngine\application\assets\degree5.dcplt ${{github.workspace}}\build\Release\degree5.dcplt
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: TGAppWindows
          path: |
            ${{github.workspace}}\build\Release\TGApp.exe
            ${{github.workspace}}\build\Release\assets
            ${{github.workspace}}\build\Release\degree5.dcplt
          if-no-files-found: error
          
  build_linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Update apt
        run: |
          wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.3.216-focal.list https://packages.lunarg.com/vulkan/1.3.216/lunarg-vulkan-1.3.216-focal.list
          sudo apt update
          sudo apt install vulkan-sdk
      - name: Update Clang
        run: sudo apt install clang-14 --install-suggests
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3.0.6
        with:
           path: ${{github.workspace}}/build/_deps
           key: linuxcache
      - name: Configure CMake
        run: cmake ./TGEngine -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_COMPILER=clang++
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Copy
        run: |
          cp -r ${{github.workspace}}/TGEngine/application/assets/ ${{github.workspace}}/build/
          cp -r ${{github.workspace}}/TGEngine/test/assets/*.* ${{github.workspace}}/build/assets/
          cp -r ${{github.workspace}}/TGEngine/application/assets/degree5.dcplt ${{github.workspace}}/build/degree5.dcplt
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: TGAppLinux
          path: |
            ${{github.workspace}}/build/TGApp
            ${{github.workspace}}/build/assets
            ${{github.workspace}}/build/degree5.dcplt
          if-no-files-found: error
